FROM armv7/armhf-ubuntu:15.04

ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

MAINTAINER <datajerk@gmail.com>

COPY local /usr/local/

RUN apt-get -y update && apt-get -y dist-upgrade
RUN apt-get -y install $(cat /usr/local/deps.txt)
 
RUN ldconfig

RUN useradd -u 2000 bitcoin -d /tmp/bitcoin_data

USER bitcoin

EXPOSE 8333

ENTRYPOINT /usr/local/bin/bitcoind -datadir=$DATADIR -par=$VER_THREADS

